version: '2.7'

rpc:
    listen: tcp://127.0.0.1:6001

server:
    command: "php app.php"
    relay: pipes

# queue and jobs
jobs:
    consume: [ "local" ]
    pool:
        num_workers: 2
        supervisor:
            max_worker_memory: 100

# grpc service configuration.
grpc:
    listen: "tcp://0.0.0.0:50051"
    proto:
        - "proto/service.proto"
    tls:
        key: "app.key"
        cert: "app.crt"
    pool:
        num_workers: 2
        supervisor:
            max_worker_memory: 100
